# Generated by Django 3.0.8 on 2020-08-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='fixture',
        ),
        migrations.AddField(
            model_name='post',
            name='competition',
            field=models.CharField(default='E.g. League', max_length=255),
        ),
    ]
