# Generated by Django 3.0.8 on 2020-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubnews', '0004_post_tab_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/club_images/'),
        ),
    ]
